### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by lfatty** [apuigsech/seekret#1]
I want to thank you for the great work and I believe this tool is very useful, however I got some errors during installation. See below.

**_inspect.go:27: x.Buffer undefined (type *bufio.Scanner has no field or method Buffer)_**
**_inspect.go:28: x.Buffer undefined (type *bufio.Scanner has no field or method Buffer)_**

**Comment by apuigsech** [comment]
Which version of golang you are using?

**Comment by apuigsech** [comment]
This is a problem that happens on golang < 1.6 because the method Buffer don't exists.

If you need to build it, you can just remove those two lines and it should work in the vast majority of cases, since this Buffer call is there to manage big files.
