### ISSUE TITLE
type *bufio.Scanner has no field or method Buffer

### ISSUE THREAD

**Issue by taylorwin** [apuigsech/seekret#3]
root@kali:/taylor# go get github.com/apuigsech/seekret/cmd/seekret
# github.com/apuigsech/seekret/lib

src/github.com/apuigsech/seekret/lib/inspect.go:27: x.Buffer undefined (type *bufio.Scanner has no field or method Buffer)
src/github.com/apuigsech/seekret/lib/inspect.go:28: x.Buffer undefined (type *bufio.Scanner has no field or method Buffer)

**Comment by apuigsech** [comment]
This is a problem that happens on golang < 1.6 because the method Buffer don't exists.

If you need to build it, you can just remove those two lines and it should work in the vast majority of cases, since this Buffer call is there to manage big files.
