### ISSUE TITLE
Could not "go get" on Fedora

### ISSUE THREAD

**Issue by bdenning** [apuigsech/seekret#5]
Hi,

This looked like an interesting project, but I seem to be unable to compile the binary. Possibly this is a Fedora specific problem due to either missing config or a missing dependency? I'm using Fedora 23.

I've run:

```
$ sudo dnf -y install libgit2
$ go get github.com/apuigsech/seekret/cmd/seekret
```

And receive the following error:

```
# github.com/libgit2/git2go
could not determine kind of name for C.GIT_CONFIG_LEVEL_PROGRAMDATA
could not determine kind of name for C.git_config_find_programdata
```

**Comment by bdenning** [comment]
Looks like this issue may hold the answer to the problem:
https://github.com/libgit2/git2go/issues/281

I have libgit2-devel 0.23.4 installed. I may see, time permitting, if I can get it working by checking out a version of git2go that matches my installed version, as per the INSTALLING section from the git2go README.

**Comment by apuigsech** [comment]
This issue is related to the libgit2 version you are using, that seems to be non compatible with github.com/libgit2/git2go. 

I am using libgit 0.24.1 and the commit 8eaae73f85dd3df78df80d2dac066eb0866444ae of github.com/libgit2/git2go.

Try to update your libgit2 to 0.24.1.
