### ISSUE TITLE
Compiled binaries to download

### ISSUE THREAD

**Issue by jcscottiii** [apuigsech/seekret#6]
In order to use this in a scriptable way that does not require the installation of Go, it would be useful to have compiled binaries to download.
Could use something like goxc

**Comment by apuigsech** [comment]
I will take a look about how to generate the artifacts/binaries for several systems and architectures by using travis-ci.

If you have a clear idea about how to do it, feel free to PR :)

**Comment by jcscottiii** [comment]
There are some instructions on how to setup goxc here. (This is for a project I contribute to)
https://github.com/opencontrol/compliance-masonry/blob/master/CONTRIBUTING.md#creating-binaries

We don't currently have it setup in CI. goxc will build and create a tag for you in Github.

**Comment by apuigsech** [comment]
I will do that with git-seekret (https://github.com/apuigsech/git-seekret) but not with the 'seekret' cmd included here, as it is just an example.
