### ISSUE TITLE
Possibility to look at only staged revision 

### ISSUE THREAD

**Issue by jcscottiii** [apuigsech/seekret#7]
In order to use this as a pre-commit hook, would be helpful if you could look at just the staged revision / before the commit is actually made.

Example of the `--staged` flag here:
https://github.com/emanuelfeld/poirot#running-poirot-from-the-command-line

**Comment by apuigsech** [comment]
It's already posible; seekret git -s <path>

BTW, take a look at https://github.com/apuigsech/git-seekret I think could be interesting for your use case.

**Comment by jcscottiii** [comment]
@apuigsech Thanks!! I would really want to get a binary download of that tool!
