### ISSUE TITLE
Not working as expected on directories?

### ISSUE THREAD

**Issue by berlincount** [apuigsech/seekret#8]
$ seekret --rules ${GOPATH}/src/github.com/apuigsech/seekret/rules dir --recursive . ; echo $?

0
$ rgrep -- '-----BEGIN RSA PRIVATE KEY-----' .
./.ssh/id_rsa:-----BEGIN RSA PRIVATE KEY-----
$ go version
go version go1.7.1 linux/amd64

What am I doing wrong?

**Comment by apuigsech** [comment]
Please, can you try again adding the --hidden parameter? It should work.

**Comment by apuigsech** [comment]
I found some issues. Fixing them!

**Comment by apuigsech** [comment]
Fixed on this commit https://github.com/apuigsech/seekret/commit/faed229c3483d38daaae34c48a305c42ec149505
